---
#- name: Installing python3-pip packages using apt
#  become: true
#  apt:
#    pkg: "python3-pip"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'Ubuntu'

#- name: Installing python3-pip packages using yum
#  become: true
#  yum:
#    pkg: "python3-pip"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#- name: Installing python3-pip packages using pacman
#  pacman:
#    name: "python3-pip"
#    state: present
#  when: ansible_distribution == 'MacOSX'

- name: Installing python3-pip packages
  become: true
  package:
    name: "python3-pip"
    state: present
